version: '3.7'

services:

  web:
    container_name: jovaitas_web
    build: docker
    ports:
      - 5000:80
    volumes:
      - .:/var/www:delegated
    links :
      - db:drupal_db
    depends_on:
      - db

  db:
    container_name: jovaitas_db
    image: mysql:5.5
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=root
