#!/usr/bin/env bash

## Sets up environment for development

fin drush rr

# Enable/disable modules for dev
fin drush en dblog -y
fin drush en simpletest -y
fin drush dis google_recaptcha -y

# Variables
fin drush vset preprocess_css 0 -y
fin drush vset preprocess_js 0 -y

# Always remember to flush
fin drush cc all
