<?php

/**
 * @file
 * Functions for jovaitas_topbar module.
 */

/**
 * Implements hook_block_info().
 */
function jovaitas_topbar_block_info() {

  $blocks = [];

  $blocks['block_top_bar'] = [
    'info' => t('Jovaitas: Viršutinė juosta.'),
    'cache' => DRUPAL_NO_CACHE,
  ];

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function jovaitas_topbar_block_configure($delta = '') {

  $form = [];

  switch ($delta) {
    case 'block_top_bar':
      $form['top_bar_content'] = [
        '#type' => 'text_format',
        '#title' => t('Turinys'),
        '#description' => t('Įrašykite viršutinės juostos tekstą.'),
        '#default_value' => variable_get('jovaitas_topbar_content', t('Viršutinės juostos tekstas.')),
      ];
      break;
  }

  return $form;
}

/**
 * Implements hook_form_alter().
 */
function jovaitas_topbar_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {
    case 'block_admin_configure':
      $form['#after_build'][] = 'jovaitas_topbar_block_form_after_build';
      break;
  }
}

/**
 * Block Form after_build function.
 */
function jovaitas_topbar_block_form_after_build($form) {

  // Remove unwanted form fields.
  unset($form['settings']['title']);
  unset($form['settings']['top_bar_content']['format']['guidelines']);
  unset($form['regions']);
  unset($form['visibility_title']);
  unset($form['visibility']);

  // Alter form.
  $form['settings']['top_bar_content']['format']['#attributes'] = ['hidden' => TRUE];
  $form['actions']['submit']['#value'] = t('Išsaugoti');

  return $form;
}

/**
 * Implements hook_block_save().
 */
function jovaitas_topbar_block_save($delta = '', $edit = []) {

  // We need to save settings from the configuration form.
  // We need to check $delta to make sure we are saving the right block.
  switch ($delta) {
    case 'block_top_bar':
      // Have Drupal save the string to the database.
      variable_set('jovaitas_topbar_content', $edit['top_bar_content']['value']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function jovaitas_topbar_block_view($delta = '') {

  $block = [];

  switch ($delta) {
    case 'block_top_bar':
      $block['subject'] = t('Viršutinės juostos blockas.');
      $block['content'] = jovaitas_topbar_content_callback();
      break;
  }

  return $block;
}

/**
 * Callback for block content.
 *
 * @return string
 *   Html string.
 */
function jovaitas_topbar_content_callback() {

  $content = variable_get('jovaitas_topbar_content', t('Viršutinės juostos tekstas.'));

  $edit_url = '/admin/structure/block/manage/jovaitas_topbar/block_top_bar/configure';
  return theme('jovaitas_topbar_template', [
    'content' => $content,
    'edit_url' => $edit_url,
  ]);
}

/**
 * Implements hook_theme().
 */
function jovaitas_topbar_theme() {
  return [
    'jovaitas_topbar_template' => [
      'template' => 'jovaitas-topbar',
    ],
  ];
}
