<?php

/**
 * @file
 * Module file for Jovaitas Module
 */


// Include all admin settings form
module_load_include('inc', 'jovaitas', 'includes/admin.settings');

function is_shop_admin() {
  
  global $user;
  $shop_admin = FALSE;

  if (in_array('administrator', array_values($user->roles)) || in_array('editor', array_values($user->roles))) {
    $shop_admin = TRUE;
  }
  return $shop_admin;
}

/**
 * Implements hook_user_login(). 
 */
// function jovaitas_user_login(&$edit, $account) {
// 	$message = variable_get('welcome_message', 'welcome');
//   	drupal_set_message(check_plain(t($message)));
// }


/**
 * Implements hook_menu().
 */
// function jovaitas_menu() {
  // $items['grazinimai'] = array(
  //   'title' => t('Grąžinimai'),
  //   'page callback' => 'drupal_get_form',
  //   'page arguments' => array('grazinimai_form'),
  //   'access callback' => TRUE,
  //   'weight'=> 1,
  //   'type'=> MENU_NORMAL_ITEM,
  // );
//   return $items;
// }

// function grazinimai_form($form, &$form_submit) {
//   $form['firstname'] = array(
//     '#title' => t('First Name'),
//     '#type' => 'textfield',
//     //'#required' => TRUE,
//   );
//   $form['lastname'] = array(
//     '#title' => t('Client Name'),
//     '#type' => 'textfield',
//     //'#required' => TRUE,
//   );
//   $form['submit'] = array(
//     '#value' => 'Test',
//     '#type' => 'submit',
//   );
//   return $form;
// }

// function grazinimai_form_form_submit($form_id, &$form_state) {

// }

// function jovaitas_commerce_line_item_type_info() {
//   $line_item_types = array();
 
//   $line_item_types['naujausias'] = array(
//     'type' => 'naujausias', 
//     'name' => t('Naujausias'), 
//     'description' => t('Nuajausiu prekiu isdestymas.'), 
//     'product' => TRUE, 
//     'add_form_submit_value' => t('Add product'), 
//     'base' => 'commerce_product_line_item',
//   );
 
//   return $line_item_types;
// }